import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to the <a href="">Randomness!</a>
        </h1>

        <p className={styles.description}>Let's get started</p>

        <div className={styles.grid}>
          <Link href="/works">
            <div className={styles.card}>
              <h2>Works &rarr;</h2>
              <p>Random works from art created by coding.</p>
            </div>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>Made with Curiosity</footer>
    </div>
  );
}
